from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass(frozen=True)
class BodyDefinition:
    id: str
    name: str
    command: str | None
    body_type: str
    parent: str | None
    radius_km: float
    mass_kg: float | None
    orbital_period_days: float | None
    semimajor_axis_km: float | None
    color: str
    description: str
    phase: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


BODY_DEFINITIONS: tuple[BodyDefinition, ...] = (
    BodyDefinition(
        id="sun",
        name="Sun",
        command="10",
        body_type="star",
        parent=None,
        radius_km=696_340,
        mass_kg=1.9885e30,
        orbital_period_days=None,
        semimajor_axis_km=0,
        color="#f8c252",
        description="The central star of the Solar System.",
    ),
    BodyDefinition(
        id="mercury",
        name="Mercury",
        command="199",
        body_type="planet",
        parent="sun",
        radius_km=2_439.7,
        mass_kg=3.3011e23,
        orbital_period_days=87.969,
        semimajor_axis_km=57_909_050,
        color="#b7b8ba",
        description="The innermost planet.",
        phase=0.12,
    ),
    BodyDefinition(
        id="venus",
        name="Venus",
        command="299",
        body_type="planet",
        parent="sun",
        radius_km=6_051.8,
        mass_kg=4.8675e24,
        orbital_period_days=224.701,
        semimajor_axis_km=108_208_000,
        color="#ddbe7a",
        description="Second planet from the Sun.",
        phase=0.23,
    ),
    BodyDefinition(
        id="earth",
        name="Earth",
        command="399",
        body_type="planet",
        parent="sun",
        radius_km=6_371.0,
        mass_kg=5.97237e24,
        orbital_period_days=365.256,
        semimajor_axis_km=149_598_023,
        color="#4f8df0",
        description="Our home planet.",
        phase=0.31,
    ),
    BodyDefinition(
        id="moon",
        name="Moon",
        command="301",
        body_type="moon",
        parent="earth",
        radius_km=1_737.4,
        mass_kg=7.342e22,
        orbital_period_days=27.322,
        semimajor_axis_km=384_400,
        color="#c8c8c8",
        description="Earth's natural satellite.",
        phase=0.71,
    ),
    BodyDefinition(
        id="mars",
        name="Mars",
        command="499",
        body_type="planet",
        parent="sun",
        radius_km=3_389.5,
        mass_kg=6.4171e23,
        orbital_period_days=686.980,
        semimajor_axis_km=227_939_200,
        color="#cc6f4e",
        description="The red planet.",
        phase=0.44,
    ),
    BodyDefinition(
        id="phobos",
        name="Phobos",
        command="401",
        body_type="moon",
        parent="mars",
        radius_km=11.2667,
        mass_kg=1.0659e16,
        orbital_period_days=0.319,
        semimajor_axis_km=9_376,
        color="#99866d",
        description="Largest moon of Mars.",
        phase=0.08,
    ),
    BodyDefinition(
        id="deimos",
        name="Deimos",
        command="402",
        body_type="moon",
        parent="mars",
        radius_km=6.2,
        mass_kg=1.4762e15,
        orbital_period_days=1.263,
        semimajor_axis_km=23_458,
        color="#c2ab8a",
        description="Outer moon of Mars.",
        phase=0.42,
    ),
    BodyDefinition(
        id="jupiter",
        name="Jupiter",
        command="599",
        body_type="planet",
        parent="sun",
        radius_km=69_911,
        mass_kg=1.8982e27,
        orbital_period_days=4_332.589,
        semimajor_axis_km=778_340_821,
        color="#d8b187",
        description="The largest planet in the Solar System.",
        phase=0.54,
    ),
    BodyDefinition(
        id="io",
        name="Io",
        command="501",
        body_type="moon",
        parent="jupiter",
        radius_km=1_821.6,
        mass_kg=8.9319e22,
        orbital_period_days=1.769,
        semimajor_axis_km=421_700,
        color="#cbb26d",
        description="Innermost Galilean moon.",
        phase=0.17,
    ),
    BodyDefinition(
        id="europa",
        name="Europa",
        command="502",
        body_type="moon",
        parent="jupiter",
        radius_km=1_560.8,
        mass_kg=4.7998e22,
        orbital_period_days=3.551,
        semimajor_axis_km=671_100,
        color="#b8b3c8",
        description="Icy Galilean moon.",
        phase=0.62,
    ),
    BodyDefinition(
        id="ganymede",
        name="Ganymede",
        command="503",
        body_type="moon",
        parent="jupiter",
        radius_km=2_634.1,
        mass_kg=1.4819e23,
        orbital_period_days=7.155,
        semimajor_axis_km=1_070_400,
        color="#9a8f7d",
        description="Largest moon in the Solar System.",
        phase=0.86,
    ),
    BodyDefinition(
        id="callisto",
        name="Callisto",
        command="504",
        body_type="moon",
        parent="jupiter",
        radius_km=2_410.3,
        mass_kg=1.0759e23,
        orbital_period_days=16.689,
        semimajor_axis_km=1_882_700,
        color="#7d796f",
        description="Outer Galilean moon.",
        phase=0.28,
    ),
    BodyDefinition(
        id="amalthea",
        name="Amalthea",
        command="505",
        body_type="moon",
        parent="jupiter",
        radius_km=83.5,
        mass_kg=2.08e18,
        orbital_period_days=0.498,
        semimajor_axis_km=181_366,
        color="#b78963",
        description="Inner moon of Jupiter.",
        phase=0.52,
    ),
    BodyDefinition(
        id="thebe",
        name="Thebe",
        command="514",
        body_type="moon",
        parent="jupiter",
        radius_km=49.3,
        mass_kg=4.3e17,
        orbital_period_days=0.675,
        semimajor_axis_km=221_889,
        color="#8f6f58",
        description="Inner moon of Jupiter outside Amalthea.",
        phase=0.66,
    ),
    BodyDefinition(
        id="adrastea",
        name="Adrastea",
        command="515",
        body_type="moon",
        parent="jupiter",
        radius_km=8.2,
        mass_kg=2.0e15,
        orbital_period_days=0.299,
        semimajor_axis_km=129_000,
        color="#9f8a77",
        description="Small inner moon embedded near Jupiter's main ring.",
        phase=0.41,
    ),
    BodyDefinition(
        id="metis",
        name="Metis",
        command="516",
        body_type="moon",
        parent="jupiter",
        radius_km=21.5,
        mass_kg=9.56e16,
        orbital_period_days=0.295,
        semimajor_axis_km=128_000,
        color="#a28e7e",
        description="Innermost known moon of Jupiter.",
        phase=0.24,
    ),
    BodyDefinition(
        id="himalia",
        name="Himalia",
        command="506",
        body_type="moon",
        parent="jupiter",
        radius_km=69.8,
        mass_kg=4.2e18,
        orbital_period_days=250.566,
        semimajor_axis_km=11_461_000,
        color="#8a847e",
        description="Largest irregular moon in Jupiter's Himalia group.",
        phase=0.72,
    ),
    BodyDefinition(
        id="elara",
        name="Elara",
        command="507",
        body_type="moon",
        parent="jupiter",
        radius_km=43.0,
        mass_kg=8.7e17,
        orbital_period_days=259.652,
        semimajor_axis_km=11_740_000,
        color="#7e7872",
        description="Irregular prograde moon of Jupiter.",
        phase=0.11,
    ),
    BodyDefinition(
        id="pasiphae",
        name="Pasiphae",
        command="508",
        body_type="moon",
        parent="jupiter",
        radius_km=28.9,
        mass_kg=2.99e17,
        orbital_period_days=743.63,
        semimajor_axis_km=23_624_000,
        color="#6f6861",
        description="Irregular retrograde moon and namesake of the Pasiphae group.",
        phase=0.57,
    ),
    BodyDefinition(
        id="sinope",
        name="Sinope",
        command="509",
        body_type="moon",
        parent="jupiter",
        radius_km=19.0,
        mass_kg=7.5e16,
        orbital_period_days=758.90,
        semimajor_axis_km=23_939_000,
        color="#8b6c5d",
        description="Outer retrograde irregular moon of Jupiter.",
        phase=0.33,
    ),
    BodyDefinition(
        id="carme",
        name="Carme",
        command="511",
        body_type="moon",
        parent="jupiter",
        radius_km=23.0,
        mass_kg=1.3e17,
        orbital_period_days=702.84,
        semimajor_axis_km=22_600_000,
        color="#7f5e54",
        description="Retrograde irregular moon and largest body in the Carme group.",
        phase=0.85,
    ),
    BodyDefinition(
        id="ananke",
        name="Ananke",
        command="512",
        body_type="moon",
        parent="jupiter",
        radius_km=14.0,
        mass_kg=3.8e16,
        orbital_period_days=629.77,
        semimajor_axis_km=21_280_000,
        color="#7b756e",
        description="Retrograde irregular moon and namesake of the Ananke group.",
        phase=0.48,
    ),
    BodyDefinition(
        id="saturn",
        name="Saturn",
        command="699",
        body_type="planet",
        parent="sun",
        radius_km=58_232,
        mass_kg=5.6834e26,
        orbital_period_days=10_759.22,
        semimajor_axis_km=1_426_666_422,
        color="#d9c07b",
        description="Gas giant known for its rings.",
        phase=0.63,
    ),
    BodyDefinition(
        id="mimas",
        name="Mimas",
        command="601",
        body_type="moon",
        parent="saturn",
        radius_km=198.2,
        mass_kg=3.749e19,
        orbital_period_days=0.942,
        semimajor_axis_km=185_540,
        color="#c3c2bf",
        description="Small innermost major moon of Saturn.",
        phase=0.05,
    ),
    BodyDefinition(
        id="enceladus",
        name="Enceladus",
        command="602",
        body_type="moon",
        parent="saturn",
        radius_km=252.1,
        mass_kg=1.08e20,
        orbital_period_days=1.370,
        semimajor_axis_km=237_948,
        color="#d9ecf7",
        description="Icy moon with active geysers.",
        phase=0.14,
    ),
    BodyDefinition(
        id="tethys",
        name="Tethys",
        command="603",
        body_type="moon",
        parent="saturn",
        radius_km=531.1,
        mass_kg=6.174e20,
        orbital_period_days=1.888,
        semimajor_axis_km=294_672,
        color="#cecfcf",
        description="Mid-sized icy moon of Saturn.",
        phase=0.26,
    ),
    BodyDefinition(
        id="dione",
        name="Dione",
        command="604",
        body_type="moon",
        parent="saturn",
        radius_km=561.4,
        mass_kg=1.095e21,
        orbital_period_days=2.737,
        semimajor_axis_km=377_415,
        color="#d6d1c8",
        description="Icy moon of Saturn.",
        phase=0.36,
    ),
    BodyDefinition(
        id="rhea",
        name="Rhea",
        command="605",
        body_type="moon",
        parent="saturn",
        radius_km=763.8,
        mass_kg=2.3065e21,
        orbital_period_days=4.518,
        semimajor_axis_km=527_108,
        color="#b3aba0",
        description="Second-largest moon of Saturn.",
        phase=0.47,
    ),
    BodyDefinition(
        id="titan",
        name="Titan",
        command="606",
        body_type="moon",
        parent="saturn",
        radius_km=2_574.7,
        mass_kg=1.3452e23,
        orbital_period_days=15.945,
        semimajor_axis_km=1_221_870,
        color="#d8a86f",
        description="Largest moon of Saturn.",
        phase=0.79,
    ),
    BodyDefinition(
        id="hyperion",
        name="Hyperion",
        command="607",
        body_type="moon",
        parent="saturn",
        radius_km=135.0,
        mass_kg=5.6e18,
        orbital_period_days=21.277,
        semimajor_axis_km=1_481_010,
        color="#9f8d72",
        description="Irregular moon of Saturn.",
        phase=0.12,
    ),
    BodyDefinition(
        id="iapetus",
        name="Iapetus",
        command="608",
        body_type="moon",
        parent="saturn",
        radius_km=734.5,
        mass_kg=1.8056e21,
        orbital_period_days=79.321,
        semimajor_axis_km=3_560_820,
        color="#a8a089",
        description="Two-tone moon of Saturn.",
        phase=0.31,
    ),
    BodyDefinition(
        id="phoebe",
        name="Phoebe",
        command="609",
        body_type="moon",
        parent="saturn",
        radius_km=106.5,
        mass_kg=8.292e18,
        orbital_period_days=550.48,
        semimajor_axis_km=12_952_000,
        color="#8e8881",
        description="Outer irregular moon of Saturn.",
        phase=0.58,
    ),
    BodyDefinition(
        id="uranus",
        name="Uranus",
        command="799",
        body_type="planet",
        parent="sun",
        radius_km=25_362,
        mass_kg=8.6810e25,
        orbital_period_days=30_688.5,
        semimajor_axis_km=2_870_658_186,
        color="#8fd3e8",
        description="Ice giant with a high axial tilt.",
        phase=0.08,
    ),
    BodyDefinition(
        id="puck",
        name="Puck",
        command="715",
        body_type="moon",
        parent="uranus",
        radius_km=81.0,
        mass_kg=2.9e18,
        orbital_period_days=0.762,
        semimajor_axis_km=86_004,
        color="#b9b7b2",
        description="Inner moon of Uranus.",
        phase=0.19,
    ),
    BodyDefinition(
        id="miranda",
        name="Miranda",
        command="705",
        body_type="moon",
        parent="uranus",
        radius_km=235.8,
        mass_kg=6.59e19,
        orbital_period_days=1.413,
        semimajor_axis_km=129_390,
        color="#c8c8bb",
        description="Innermost major moon of Uranus.",
        phase=0.25,
    ),
    BodyDefinition(
        id="ariel",
        name="Ariel",
        command="701",
        body_type="moon",
        parent="uranus",
        radius_km=578.9,
        mass_kg=1.251e21,
        orbital_period_days=2.520,
        semimajor_axis_km=191_020,
        color="#dadad4",
        description="Bright moon of Uranus.",
        phase=0.43,
    ),
    BodyDefinition(
        id="umbriel",
        name="Umbriel",
        command="702",
        body_type="moon",
        parent="uranus",
        radius_km=584.7,
        mass_kg=1.275e21,
        orbital_period_days=4.144,
        semimajor_axis_km=266_300,
        color="#8a8785",
        description="Dark moon of Uranus.",
        phase=0.67,
    ),
    BodyDefinition(
        id="titania",
        name="Titania",
        command="703",
        body_type="moon",
        parent="uranus",
        radius_km=788.9,
        mass_kg=3.527e21,
        orbital_period_days=8.706,
        semimajor_axis_km=435_910,
        color="#c7c2b6",
        description="Largest moon of Uranus.",
        phase=0.89,
    ),
    BodyDefinition(
        id="oberon",
        name="Oberon",
        command="704",
        body_type="moon",
        parent="uranus",
        radius_km=761.4,
        mass_kg=3.014e21,
        orbital_period_days=13.463,
        semimajor_axis_km=583_520,
        color="#9f968a",
        description="Outermost major moon of Uranus.",
        phase=0.11,
    ),
    BodyDefinition(
        id="neptune",
        name="Neptune",
        command="899",
        body_type="planet",
        parent="sun",
        radius_km=24_622,
        mass_kg=1.02413e26,
        orbital_period_days=60_182,
        semimajor_axis_km=4_498_396_441,
        color="#4065db",
        description="Farthest major planet.",
        phase=0.18,
    ),
    BodyDefinition(
        id="naiad",
        name="Naiad",
        command="803",
        body_type="moon",
        parent="neptune",
        radius_km=33.0,
        mass_kg=1.9e17,
        orbital_period_days=0.294,
        semimajor_axis_km=48_224,
        color="#9ba1b7",
        description="Innermost moon of Neptune.",
        phase=0.09,
    ),
    BodyDefinition(
        id="thalassa",
        name="Thalassa",
        command="804",
        body_type="moon",
        parent="neptune",
        radius_km=41.0,
        mass_kg=3.5e17,
        orbital_period_days=0.311,
        semimajor_axis_km=50_075,
        color="#a6abc0",
        description="Inner moon of Neptune.",
        phase=0.22,
    ),
    BodyDefinition(
        id="despina",
        name="Despina",
        command="805",
        body_type="moon",
        parent="neptune",
        radius_km=75.0,
        mass_kg=2.1e18,
        orbital_period_days=0.335,
        semimajor_axis_km=52_526,
        color="#b1b3c0",
        description="Inner moon of Neptune.",
        phase=0.35,
    ),
    BodyDefinition(
        id="galatea",
        name="Galatea",
        command="806",
        body_type="moon",
        parent="neptune",
        radius_km=88.0,
        mass_kg=2.12e18,
        orbital_period_days=0.429,
        semimajor_axis_km=61_953,
        color="#aab0c3",
        description="Inner moon of Neptune.",
        phase=0.44,
    ),
    BodyDefinition(
        id="larissa",
        name="Larissa",
        command="807",
        body_type="moon",
        parent="neptune",
        radius_km=97.9,
        mass_kg=4.2e18,
        orbital_period_days=0.555,
        semimajor_axis_km=73_548,
        color="#9ea5bb",
        description="Inner moon of Neptune.",
        phase=0.61,
    ),
    BodyDefinition(
        id="proteus",
        name="Proteus",
        command="808",
        body_type="moon",
        parent="neptune",
        radius_km=210.0,
        mass_kg=4.4e19,
        orbital_period_days=1.122,
        semimajor_axis_km=117_647,
        color="#969db0",
        description="Second-largest moon of Neptune.",
        phase=0.73,
    ),
    BodyDefinition(
        id="triton",
        name="Triton",
        command="801",
        body_type="moon",
        parent="neptune",
        radius_km=1_353.4,
        mass_kg=2.139e22,
        orbital_period_days=5.877,
        semimajor_axis_km=354_759,
        color="#c4c6ce",
        description="Largest moon of Neptune.",
        phase=0.53,
    ),
    BodyDefinition(
        id="nereid",
        name="Nereid",
        command="802",
        body_type="moon",
        parent="neptune",
        radius_km=170.0,
        mass_kg=3.1e19,
        orbital_period_days=360.136,
        semimajor_axis_km=5_513_818,
        color="#9b9eb6",
        description="Irregular outer moon of Neptune.",
        phase=0.77,
    ),
)

BODY_BY_ID = {body.id: body for body in BODY_DEFINITIONS}
MOON_IDS = {body.id for body in BODY_DEFINITIONS if body.body_type == "moon"}
